export enum ActionType {
    GET_ALL_ACTIVITIES='GET_ALL_ACTIVITIES',
    SELECT_ACTIVITY='SELECT_ACTIVITY',
    CANCEL_SELECT_ACTIVITY='CANCEL_SELECT_ACTIVITY',
    OPEN_EDIT_MODE='OPEN_EDIT_MODE',
    CLOSE_EDIT_MODE='CLOSE_EDIT_MODE',
    FETCH_ACTIVITIES_PENDING='FETCH_ACTIVITIES_PENDING',
    FETCH_ACTIVITIES_SUCCESS='FETCH_ACTIVITIES_SUCCESS',
    FETCH_ACTIVITIES_ERROR='FETCH_ACTIVITIES_ERROR',
}